title: "Clase Estadística Aplicada a Diseño de Experimentos"
description: "Sitio web creado con Jekyll para GitHub Pages"

url: "https://cihernand.github.io"
baseurl: "/sitioclase"

lang: "es"
timezone: "Europe/Madrid"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
